import {Dimensions, StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  title: {
    fontWeight: '500',
    color: '#1d1c1c',
  },
  bondedDevice: {
    height: 58,
    justifyContent: 'space-between',
    width: '100%',
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 5,
    borderTopWidth: 1,
    borderColor: '#b3c6eb',
  },
  flex1: {
    flex: 1,
  },
  openAccordionArrow: {
    transform: [{rotate: '90deg'}],
  },
  closedAccordionArrow: {
    transform: [{rotate: '-90deg'}],
  },
  body: {
    paddingBottom: 15,
    paddingTop: 15,
    marginHorizontal: 20,
    gap: 15,
  },
  permissionsBody: {
    height: Dimensions.get('window').height - 50,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  accordionButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  connectionControl: {
    borderRadius: 6,
    backgroundColor: '#e8f0ff',
    borderColor: '#b3c6eb',
    paddingHorizontal: 8,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
  },
  alarmConfig: {
    borderRadius: 6,
    backgroundColor: '#fffdf2',
    borderColor: '#d7c479',
    paddingHorizontal: 8,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
  },
  dateTimeRow: {
    flexDirection: 'row',
    width: ' 100%',
    gap: 15,
  },
  dateTimeSetter: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderColor: '#dfab00',
    borderWidth: 2,
  },
  header: {
    zIndex: 10,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    justifyContent: 'center',
    borderColor: '#18979c',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    width: '100%',
  },
  headerText: {
    color: '#18979c',
    letterSpacing: 1,
    textShadowColor: '#2a2a2a',
    textShadowRadius: 2,
    textShadowOffset: {height: 1, width: 0},
    fontWeight: '600',
  },
  logo: {
    position: 'absolute',
    right: 0,
    alignSelf: 'center',
    height: 50,
    width: 50,
  },
  dateTimeSetterText: {
    color: '#dfab00',
  },
  alarmSetter: {
    paddingVertical: 12,
    flex: 1,
    backgroundColor: '#ba8e00',
  },
  deviceControl: {
    borderTopWidth: 1,
    borderTopColor: '#d7c479',
    gap: 6,
    paddingHorizontal: 10,
    paddingTop: 5,
    paddingBottom: 10,
  },
});
